version: 0.2

env:
  variables:
    STACK_NAME: "eksctl-yhdEks-cluster"

phases:
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install awscli --upgrade
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin
      - eksctl version

  build:
    commands:
      - echo Build started on `date`
      # Environment drift detection
      - /bin/sh script/create-eks.sh $STACK_NAME
      #- eksctl scale nodegroup --cluster=yhdEks --nodes=5, --name=ng-e56250ca
      #- kubectl scale $DEPLOYMENT dso-demo --replicas=3

      # EncryptionConfig detection

  post_build:
    commands:
      - echo Build completed on `date`

#artifacts:
#  files:
#    - infrastructure/* 
#cache:
#  paths:
#    - '/root/.m2/**/*'
