version: 0.2

env:
  variables:
    STACK_ECR: "ecr-repo"
    STACK_EKS_CLUSTER: "eksctl-yhdEks-cluster"
    STACK_EKS_NG: "eksctl-yhdEks-nodegroup-workers"

phases:
  pre_build:
    commands:
      # upgrade awscli
      - pip install --upgrade pip
      - pip install awscli --upgrade
      # sync templates to S3 bucket
      - aws s3 sync ./infrastructure/ s3://cf-templates-i6aohmzkcsjf-ap-east-1/templates/ --acl public-read

  build:
    commands:
      - echo Build started on `date`
      # Environment drift detection for ECR repository
      - /bin/sh script/check-drift.sh $STACK_ECR
      # Environment drift detection for EKS cluster
      #- /bin/sh script/check-drift.sh $STACK_EKS_CLUSTER
      # Environment drift detection for EKS cluster nodegroup
      - /bin/sh script/check-drift.sh $STACK_EKS_NG

      # EncryptionConfig detection

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Nothing to do in post_build