version: 0.2

env:
  variables:
    STACK_ECR: "ecr-repo"
    STACK_EKS_CLUSTER: "eksctl-yhdEks-cluster"

phases:
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install awscli --upgrade
      - aws s3 sync ./infrastructure/ s3://cf-templates-i6aohmzkcsjf-ap-east-1/templates/ --acl public-read
      # scale nodes
      #- eksctl scale nodegroup --cluster=yhdEks --nodes=5, --name=ng-e56250ca

  build:
    commands:
      - echo Build started on `date`
      # Environment drift detection
      - /bin/sh script/check-drift.sh $STACK_ECR
      - /bin/sh script/check-drift.sh $STACK_EKS_CLUSTER

      # EncryptionConfig detection

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Nothing to do in post_build

#artifacts:
#  files:
#    - infrastructure/* 
#cache:
#  paths:
#    - '/root/.m2/**/*'
