AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Elastic Container Registery
Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "ecr-repo"
      ImageScanningConfiguration: 
        scanOnPush: "true"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              Service:
                - "codebuild.amazonaws.com"
              AWS: 
                - "arn:aws:iam::937127767762:user/yhd"
                - "arn:aws:iam::937127767762:user/ljx"
                - "arn:aws:iam::937127767762:role/service-role/codebuild-dev-sec-ops-demo-svc-role"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"