AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Elastic Load Balancer

Resources:
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
      - "ap-east-1a"
      - "ap-east-1b"
      # Instances:
      # - Ref: logical name of AWS::EC2::Instance resource 1
      # - Ref: logical name of AWS::EC2::Instance resource 2
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'